// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXyGNp4dnlC-stVMDana7tel3Ph9236us',
    appId: '1:318676756543:web:9a865be8ac0909e462708a',
    messagingSenderId: '318676756543',
    projectId: 'chat-ai-flutter-cc9f0',
    authDomain: 'chat-ai-flutter-cc9f0.firebaseapp.com',
    storageBucket: 'chat-ai-flutter-cc9f0.firebasestorage.app',
    measurementId: 'G-V9NQXHQ9FS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx6IGmh2rcWm3xYomCw5Nqu59sdWLO79c',
    appId: '1:318676756543:android:d2ed623420c016d962708a',
    messagingSenderId: '318676756543',
    projectId: 'chat-ai-flutter-cc9f0',
    storageBucket: 'chat-ai-flutter-cc9f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIBJ12HE1TB2BfMQKSYIRDZP5xr1rn8kM',
    appId: '1:318676756543:ios:23e7d0feabfbe9e862708a',
    messagingSenderId: '318676756543',
    projectId: 'chat-ai-flutter-cc9f0',
    storageBucket: 'chat-ai-flutter-cc9f0.firebasestorage.app',
    iosBundleId: 'com.example.chatAiFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIBJ12HE1TB2BfMQKSYIRDZP5xr1rn8kM',
    appId: '1:318676756543:ios:23e7d0feabfbe9e862708a',
    messagingSenderId: '318676756543',
    projectId: 'chat-ai-flutter-cc9f0',
    storageBucket: 'chat-ai-flutter-cc9f0.firebasestorage.app',
    iosBundleId: 'com.example.chatAiFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXyGNp4dnlC-stVMDana7tel3Ph9236us',
    appId: '1:318676756543:web:c248a97e46606c3562708a',
    messagingSenderId: '318676756543',
    projectId: 'chat-ai-flutter-cc9f0',
    authDomain: 'chat-ai-flutter-cc9f0.firebaseapp.com',
    storageBucket: 'chat-ai-flutter-cc9f0.firebasestorage.app',
    measurementId: 'G-FL9V92C89P',
  );

}